
import Head from 'next/head'



const Tuhistoria = () => {
  return (
    <>
     <Head>
        <title>Tu Historia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div>tuhistoria</div>
    </>

  )
}

export default Tuhistoria