export const municipios = [
    {"codigo":"001","nombre":"MEDELLIN","codigodepartamento":"05"},
    {"codigo":"002","nombre":"ABEJORRAL","codigodepartamento":"05"},
    {"codigo":"004","nombre":"ABRIAQUI","codigodepartamento":"05"},
    {"codigo":"021","nombre":"ALEJANDRIA","codigodepartamento":"05"},
    {"codigo":"030","nombre":"AMAGA","codigodepartamento":"05"},
    {"codigo":"031","nombre":"AMALFI","codigodepartamento":"05"},
    {"codigo":"034","nombre":"ANDES","codigodepartamento":"05"},
    {"codigo":"036","nombre":"ANGELOPOLIS","codigodepartamento":"05"},
    {"codigo":"038","nombre":"ANGOSTURA","codigodepartamento":"05"},
    {"codigo":"040","nombre":"ANORI","codigodepartamento":"05"},
    {"codigo":"042","nombre":"SANTAFE DE ANTIOQUIA","codigodepartamento":"05"},
    {"codigo":"044","nombre":"ANZA","codigodepartamento":"05"},
    {"codigo":"045","nombre":"APARTADO","codigodepartamento":"05"},
    {"codigo":"051","nombre":"ARBOLETES","codigodepartamento":"05"},
    {"codigo":"055","nombre":"ARGELIA","codigodepartamento":"05"},
    {"codigo":"059","nombre":"ARMENIA","codigodepartamento":"05"},
    {"codigo":"079","nombre":"BARBOSA","codigodepartamento":"05"},
    {"codigo":"086","nombre":"BELMIRA","codigodepartamento":"05"},
    {"codigo":"088","nombre":"BELLO","codigodepartamento":"05"},
    {"codigo":"091","nombre":"BETANIA","codigodepartamento":"05"},
    {"codigo":"093","nombre":"BETULIA","codigodepartamento":"05"},
    {"codigo":"101","nombre":"CIUDAD BOLIVAR","codigodepartamento":"05"},
    {"codigo":"107","nombre":"BRICEÑO","codigodepartamento":"05"},
    {"codigo":"113","nombre":"BURITICA","codigodepartamento":"05"},
    {"codigo":"120","nombre":"CACERES","codigodepartamento":"05"},
    {"codigo":"125","nombre":"CAICEDO","codigodepartamento":"05"},
    {"codigo":"129","nombre":"CALDAS","codigodepartamento":"05"},
    {"codigo":"134","nombre":"CAMPAMENTO","codigodepartamento":"05"},
    {"codigo":"138","nombre":"CAÑASGORDAS","codigodepartamento":"05"},
    {"codigo":"142","nombre":"CARACOLI","codigodepartamento":"05"},
    {"codigo":"145","nombre":"CARAMANTA","codigodepartamento":"05"},
    {"codigo":"147","nombre":"CAREPA","codigodepartamento":"05"},
    {"codigo":"148","nombre":"CARMEN DE VIBORAL","codigodepartamento":"05"},
    {"codigo":"150","nombre":"CAROLINA","codigodepartamento":"05"},
    {"codigo":"154","nombre":"CAUCASIA","codigodepartamento":"05"},
    {"codigo":"172","nombre":"CHIGORODO","codigodepartamento":"05"},
    {"codigo":"190","nombre":"CISNEROS","codigodepartamento":"05"},
    {"codigo":"197","nombre":"COCORNA","codigodepartamento":"05"},
    {"codigo":"206","nombre":"CONCEPCION","codigodepartamento":"05"},
    {"codigo":"209","nombre":"CONCORDIA","codigodepartamento":"05"},
    {"codigo":"212","nombre":"COPACABANA","codigodepartamento":"05"},
    {"codigo":"234","nombre":"DABEIBA","codigodepartamento":"05"},
    {"codigo":"237","nombre":"DON MATIAS","codigodepartamento":"05"},
    {"codigo":"240","nombre":"EBEJICO","codigodepartamento":"05"},
    {"codigo":"250","nombre":"EL BAGRE","codigodepartamento":"05"},
    {"codigo":"264","nombre":"ENTRERRIOS","codigodepartamento":"05"},
    {"codigo":"266","nombre":"ENVIGADO","codigodepartamento":"05"},
    {"codigo":"282","nombre":"FREDONIA","codigodepartamento":"05"},
    {"codigo":"284","nombre":"FRONTINO","codigodepartamento":"05"},
    {"codigo":"306","nombre":"GIRALDO","codigodepartamento":"05"},
    {"codigo":"308","nombre":"GIRARDOTA","codigodepartamento":"05"},
    {"codigo":"310","nombre":"GOMEZ PLATA","codigodepartamento":"05"},
    {"codigo":"313","nombre":"GRANADA","codigodepartamento":"05"},
    {"codigo":"315","nombre":"GUADALUPE","codigodepartamento":"05"},
    {"codigo":"318","nombre":"GUARNE","codigodepartamento":"05"},
    {"codigo":"321","nombre":"GUATAPE","codigodepartamento":"05"},
    {"codigo":"347","nombre":"HELICONIA","codigodepartamento":"05"},
    {"codigo":"353","nombre":"HISPANIA","codigodepartamento":"05"},
    {"codigo":"360","nombre":"ITAGUI","codigodepartamento":"05"},
    {"codigo":"361","nombre":"ITUANGO","codigodepartamento":"05"},
    {"codigo":"364","nombre":"JARDIN","codigodepartamento":"05"},
    {"codigo":"368","nombre":"JERICO","codigodepartamento":"05"},
    {"codigo":"376","nombre":"LA CEJA","codigodepartamento":"05"},
    {"codigo":"380","nombre":"LA ESTRELLA","codigodepartamento":"05"},
    {"codigo":"390","nombre":"LA PINTADA","codigodepartamento":"05"},
    {"codigo":"400","nombre":"LA UNION","codigodepartamento":"05"},
    {"codigo":"411","nombre":"LIBORINA","codigodepartamento":"05"},
    {"codigo":"425","nombre":"MACEO","codigodepartamento":"05"},
    {"codigo":"440","nombre":"MARINILLA","codigodepartamento":"05"},
    {"codigo":"467","nombre":"MONTEBELLO","codigodepartamento":"05"},
    {"codigo":"475","nombre":"MURINDO","codigodepartamento":"05"},
    {"codigo":"480","nombre":"MUTATA","codigodepartamento":"05"},
    {"codigo":"483","nombre":"NARIÑO","codigodepartamento":"05"},
    {"codigo":"490","nombre":"NECOCLI","codigodepartamento":"05"},
    {"codigo":"495","nombre":"NECHI","codigodepartamento":"05"},
    {"codigo":"501","nombre":"OLAYA","codigodepartamento":"05"},
    {"codigo":"541","nombre":"PEÑOL","codigodepartamento":"05"},
    {"codigo":"543","nombre":"PEQUE","codigodepartamento":"05"},
    {"codigo":"576","nombre":"PUEBLORRICO","codigodepartamento":"05"},
    {"codigo":"579","nombre":"PUERTO BERRIO","codigodepartamento":"05"},
    {"codigo":"585","nombre":"PUERTO NARE","codigodepartamento":"05"},
    {"codigo":"591","nombre":"PUERTO TRIUNFO","codigodepartamento":"05"},
    {"codigo":"604","nombre":"REMEDIOS","codigodepartamento":"05"},
    {"codigo":"607","nombre":"RETIRO","codigodepartamento":"05"},
    {"codigo":"615","nombre":"RIONEGRO","codigodepartamento":"05"},
    {"codigo":"628","nombre":"SABANALARGA","codigodepartamento":"05"},
    {"codigo":"631","nombre":"SABANETA","codigodepartamento":"05"},
    {"codigo":"642","nombre":"SALGAR","codigodepartamento":"05"},
    {"codigo":"647","nombre":"SAN ANDRES","codigodepartamento":"05"},
    {"codigo":"649","nombre":"SAN CARLOS","codigodepartamento":"05"},
    {"codigo":"652","nombre":"SAN FRANCISCO","codigodepartamento":"05"},
    {"codigo":"656","nombre":"SAN JERONIMO","codigodepartamento":"05"},
    {"codigo":"658","nombre":"SAN JOSE DE LA MONTAÑA","codigodepartamento":"05"},
    {"codigo":"659","nombre":"SAN JUAN DE URABA","codigodepartamento":"05"},
    {"codigo":"660","nombre":"SAN LUIS","codigodepartamento":"05"},
    {"codigo":"664","nombre":"SAN PEDRO","codigodepartamento":"05"},
    {"codigo":"665","nombre":"SAN PEDRO DE URABA","codigodepartamento":"05"},
    {"codigo":"667","nombre":"SAN RAFAEL","codigodepartamento":"05"},
    {"codigo":"670","nombre":"SAN ROQUE","codigodepartamento":"05"},
    {"codigo":"674","nombre":"SAN VICENTE","codigodepartamento":"05"},
    {"codigo":"679","nombre":"SANTA BARBARA","codigodepartamento":"05"},
    {"codigo":"686","nombre":"SANTA.ROSA DE OSOS","codigodepartamento":"05"},
    {"codigo":"690","nombre":"SANTO DOMINGO","codigodepartamento":"05"},
    {"codigo":"697","nombre":"SANTUARIO","codigodepartamento":"05"},
    {"codigo":"736","nombre":"SEGOVIA","codigodepartamento":"05"},
    {"codigo":"756","nombre":"SONSON","codigodepartamento":"05"},
    {"codigo":"761","nombre":"SOPETRAN","codigodepartamento":"05"},
    {"codigo":"789","nombre":"TAMESIS","codigodepartamento":"05"},
    {"codigo":"790","nombre":"TARAZA","codigodepartamento":"05"},
    {"codigo":"792","nombre":"TARSO","codigodepartamento":"05"},
    {"codigo":"809","nombre":"TITIRIBI","codigodepartamento":"05"},
    {"codigo":"819","nombre":"TOLEDO","codigodepartamento":"05"},
    {"codigo":"837","nombre":"TURBO","codigodepartamento":"05"},
    {"codigo":"842","nombre":"URAMITA","codigodepartamento":"05"},
    {"codigo":"847","nombre":"URRAO","codigodepartamento":"05"},
    {"codigo":"854","nombre":"VALDIVIA","codigodepartamento":"05"},
    {"codigo":"856","nombre":"VALPARAISO","codigodepartamento":"05"},
    {"codigo":"858","nombre":"VEGACHI","codigodepartamento":"05"},
    {"codigo":"861","nombre":"VENECIA","codigodepartamento":"05"},
    {"codigo":"873","nombre":"VIGIA DEL FUERTE","codigodepartamento":"05"},
    {"codigo":"885","nombre":"YALI","codigodepartamento":"05"},
    {"codigo":"887","nombre":"YARUMAL","codigodepartamento":"05"},
    {"codigo":"890","nombre":"YOLOMBO","codigodepartamento":"05"},
    {"codigo":"893","nombre":"YONDO","codigodepartamento":"05"},
    {"codigo":"895","nombre":"ZARAGOZA","codigodepartamento":"05"},
    {"codigo":"001","nombre":"BARRANQUILLA","codigodepartamento":"08"},
    {"codigo":"078","nombre":"BARANOA","codigodepartamento":"08"},
    {"codigo":"137","nombre":"CAMPO DE LA CRUZ","codigodepartamento":"08"},
    {"codigo":"141","nombre":"CANDELARIA","codigodepartamento":"08"},
    {"codigo":"296","nombre":"GALAPA","codigodepartamento":"08"},
    {"codigo":"372","nombre":"JUAN DE ACOSTA","codigodepartamento":"08"},
    {"codigo":"421","nombre":"LURUACO","codigodepartamento":"08"},
    {"codigo":"433","nombre":"MALAMBO","codigodepartamento":"08"},
    {"codigo":"436","nombre":"MANATI","codigodepartamento":"08"},
    {"codigo":"520","nombre":"PALMAR DE VARELA","codigodepartamento":"08"},
    {"codigo":"549","nombre":"PIOJO","codigodepartamento":"08"},
    {"codigo":"558","nombre":"POLONUEVO","codigodepartamento":"08"},
    {"codigo":"560","nombre":"PONEDERA","codigodepartamento":"08"},
    {"codigo":"573","nombre":"PUERTO COLOMBIA","codigodepartamento":"08"},
    {"codigo":"606","nombre":"REPELON","codigodepartamento":"08"},
    {"codigo":"634","nombre":"SABANAGRANDE","codigodepartamento":"08"},
    {"codigo":"638","nombre":"SABANALARGA","codigodepartamento":"08"},
    {"codigo":"675","nombre":"SANTA LUCIA","codigodepartamento":"08"},
    {"codigo":"685","nombre":"SANTO TOMAS","codigodepartamento":"08"},
    {"codigo":"758","nombre":"SOLEDAD","codigodepartamento":"08"},
    {"codigo":"770","nombre":"SUAN","codigodepartamento":"08"},
    {"codigo":"832","nombre":"TUBARA","codigodepartamento":"08"},
    {"codigo":"849","nombre":"USIACURI","codigodepartamento":"08"},
    {"codigo":"001","nombre":"USAQUEN","codigodepartamento":"11"},
    {"codigo":"002","nombre":"CAPINERO","codigodepartamento":"11"},
    {"codigo":"003","nombre":"SANTA FE ","codigodepartamento":"11"},
    {"codigo":"004","nombre":"SAN CRISTOBAL","codigodepartamento":"11"},
    {"codigo":"005","nombre":"USME","codigodepartamento":"11"},
    {"codigo":"006","nombre":"TUNJUELITO","codigodepartamento":"11"},
    {"codigo":"007","nombre":"BOSA","codigodepartamento":"11"},
    {"codigo":"008","nombre":"KENNEDY","codigodepartamento":"11"},
    {"codigo":"009","nombre":"FONTIBON","codigodepartamento":"11"},
    {"codigo":"010","nombre":"ENGATIVA","codigodepartamento":"11"},
    {"codigo":"011","nombre":"SUBA","codigodepartamento":"11"},
    {"codigo":"012","nombre":"BARRIOS UNIDOS","codigodepartamento":"11"},
    {"codigo":"013","nombre":"TEUSAQUILLO","codigodepartamento":"11"},
    {"codigo":"014","nombre":"MARTIRES","codigodepartamento":"11"},
    {"codigo":"015","nombre":"ANTONIO NARIÑO","codigodepartamento":"11"},
    {"codigo":"016","nombre":"PUENTE ARANDA","codigodepartamento":"11"},
    {"codigo":"017","nombre":"CANDELARIA","codigodepartamento":"11"},
    {"codigo":"018","nombre":"RAFAEL URIBE","codigodepartamento":"11"},
    {"codigo":"019","nombre":"CIUDAD BOLIVAR","codigodepartamento":"11"},
    {"codigo":"020","nombre":"SUMAPAZ","codigodepartamento":"11"},
    {"codigo":"001","nombre":"CARTAGENA","codigodepartamento":"13"},
    {"codigo":"006","nombre":"ACHI","codigodepartamento":"13"},
    {"codigo":"030","nombre":"ALTOS DEL ROSARIO","codigodepartamento":"13"},
    {"codigo":"042","nombre":"ARENAL","codigodepartamento":"13"},
    {"codigo":"052","nombre":"ARJONA","codigodepartamento":"13"},
    {"codigo":"062","nombre":"ARROYOHONDO","codigodepartamento":"13"},
    {"codigo":"074","nombre":"BARRANCO DE LOBA","codigodepartamento":"13"},
    {"codigo":"140","nombre":"CALAMAR","codigodepartamento":"13"},
    {"codigo":"160","nombre":"CANTAGALLO","codigodepartamento":"13"},
    {"codigo":"188","nombre":"CICUCO","codigodepartamento":"13"},
    {"codigo":"212","nombre":"CORDOBA","codigodepartamento":"13"},
    {"codigo":"222","nombre":"CLEMENCIA","codigodepartamento":"13"},
    {"codigo":"244","nombre":"EL CARMEN DE BOLIVAR","codigodepartamento":"13"},
    {"codigo":"248","nombre":"EL GUAMO","codigodepartamento":"13"},
    {"codigo":"268","nombre":"EL PENON","codigodepartamento":"13"},
    {"codigo":"300","nombre":"HATILLO DE LOBA","codigodepartamento":"13"},
    {"codigo":"430","nombre":"MAGANGUE","codigodepartamento":"13"},
    {"codigo":"433","nombre":"MAHATES","codigodepartamento":"13"},
    {"codigo":"440","nombre":"MARGARITA","codigodepartamento":"13"},
    {"codigo":"442","nombre":"MARIA LA BAJA","codigodepartamento":"13"},
    {"codigo":"458","nombre":"MONTECRISTO","codigodepartamento":"13"},
    {"codigo":"468","nombre":"MOMPOS","codigodepartamento":"13"},
    {"codigo":"473","nombre":"MORALES","codigodepartamento":"13"},
    {"codigo":"549","nombre":"PINILLOS","codigodepartamento":"13"},
    {"codigo":"580","nombre":"REGIDOR","codigodepartamento":"13"},
    {"codigo":"600","nombre":"RIO VIEJO","codigodepartamento":"13"},
    {"codigo":"620","nombre":"SAN CRISTOBAL","codigodepartamento":"13"},
    {"codigo":"647","nombre":"SAN ESTANISLAO","codigodepartamento":"13"},
    {"codigo":"650","nombre":"SAN FERNANDO","codigodepartamento":"13"},
    {"codigo":"654","nombre":"SAN JACINTO","codigodepartamento":"13"},
    {"codigo":"655","nombre":"SAN JACINTO DEL CAUCA","codigodepartamento":"13"},
    {"codigo":"657","nombre":"SAN JUAN NEPOMUCENO","codigodepartamento":"13"},
    {"codigo":"667","nombre":"SAN MARTIN DE LOBA","codigodepartamento":"13"},
    {"codigo":"670","nombre":"SAN PABLO","codigodepartamento":"13"},
    {"codigo":"673","nombre":"SANTA CATALINA","codigodepartamento":"13"},
    {"codigo":"683","nombre":"SANTA ROSA","codigodepartamento":"13"},
    {"codigo":"688","nombre":"SANTA ROSA DEL SUR","codigodepartamento":"13"},
    {"codigo":"744","nombre":"SIMITI","codigodepartamento":"13"},
    {"codigo":"760","nombre":"SOPLAVIENTO","codigodepartamento":"13"},
    {"codigo":"780","nombre":"TALAIGUA NUEVO","codigodepartamento":"13"},
    {"codigo":"810","nombre":"TIQUISIO","codigodepartamento":"13"},
    {"codigo":"836","nombre":"TURBACO","codigodepartamento":"13"},
    {"codigo":"838","nombre":"TURBANA","codigodepartamento":"13"},
    {"codigo":"873","nombre":"VILLANUEVA","codigodepartamento":"13"},
    {"codigo":"894","nombre":"ZAMBRANO","codigodepartamento":"13"},
    {"codigo":"001","nombre":"TUNJA","codigodepartamento":"15"},
    {"codigo":"022","nombre":"ALMEIDA","codigodepartamento":"15"},
    {"codigo":"047","nombre":"AQUITANIA","codigodepartamento":"15"},
    {"codigo":"051","nombre":"ARCABUCO","codigodepartamento":"15"},
    {"codigo":"087","nombre":"BELEN","codigodepartamento":"15"},
    {"codigo":"090","nombre":"BERBEO","codigodepartamento":"15"},
    {"codigo":"092","nombre":"BETEITIVA","codigodepartamento":"15"},
    {"codigo":"097","nombre":"BOAVITA","codigodepartamento":"15"},
    {"codigo":"104","nombre":"BOYACA","codigodepartamento":"15"},
    {"codigo":"106","nombre":"BRICEÑO","codigodepartamento":"15"},
    {"codigo":"109","nombre":"BUENAVISTA","codigodepartamento":"15"},
    {"codigo":"114","nombre":"BUSBANZA","codigodepartamento":"15"},
    {"codigo":"131","nombre":"CALDAS","codigodepartamento":"15"},
    {"codigo":"135","nombre":"CAMPOHERMOSO","codigodepartamento":"15"},
    {"codigo":"162","nombre":"CERINZA","codigodepartamento":"15"},
    {"codigo":"172","nombre":"CHINAVITA","codigodepartamento":"15"},
    {"codigo":"176","nombre":"CHIQUINQUIRA","codigodepartamento":"15"},
    {"codigo":"180","nombre":"CHISCAS","codigodepartamento":"15"},
    {"codigo":"183","nombre":"CHITA","codigodepartamento":"15"},
    {"codigo":"185","nombre":"CHITARAQUE","codigodepartamento":"15"},
    {"codigo":"187","nombre":"CHIVATA","codigodepartamento":"15"},
    {"codigo":"189","nombre":"CIENEGA","codigodepartamento":"15"},
    {"codigo":"204","nombre":"COMBITA","codigodepartamento":"15"},
    {"codigo":"212","nombre":"COPER","codigodepartamento":"15"},
    {"codigo":"215","nombre":"CORRALES","codigodepartamento":"15"},
    {"codigo":"218","nombre":"COVARACHIA","codigodepartamento":"15"},
    {"codigo":"223","nombre":"CUBARA","codigodepartamento":"15"},
    {"codigo":"224","nombre":"CUCAITA","codigodepartamento":"15"},
    {"codigo":"226","nombre":"CUITIVA","codigodepartamento":"15"},
    {"codigo":"232","nombre":"CHIQUIZA","codigodepartamento":"15"},
    {"codigo":"236","nombre":"CHIVOR","codigodepartamento":"15"},
    {"codigo":"238","nombre":"DUITAMA","codigodepartamento":"15"},
    {"codigo":"244","nombre":"EL COCUY","codigodepartamento":"15"},
    {"codigo":"248","nombre":"EL ESPINO","codigodepartamento":"15"},
    {"codigo":"272","nombre":"FIRAVITOBA","codigodepartamento":"15"},
    {"codigo":"276","nombre":"FLORESTA","codigodepartamento":"15"},
    {"codigo":"293","nombre":"GACHANTIVA","codigodepartamento":"15"},
    {"codigo":"296","nombre":"GAMEZA","codigodepartamento":"15"},
    {"codigo":"299","nombre":"GARAGOA","codigodepartamento":"15"},
    {"codigo":"317","nombre":"GUACAMAYAS","codigodepartamento":"15"},
    {"codigo":"322","nombre":"GUATEQUE","codigodepartamento":"15"},
    {"codigo":"325","nombre":"GUAYATA","codigodepartamento":"15"},
    {"codigo":"332","nombre":"GUICAN","codigodepartamento":"15"},
    {"codigo":"362","nombre":"IZA","codigodepartamento":"15"},
    {"codigo":"367","nombre":"JENESANO","codigodepartamento":"15"},
    {"codigo":"368","nombre":"JERICO","codigodepartamento":"15"},
    {"codigo":"377","nombre":"LABRANZAGRANDE","codigodepartamento":"15"},
    {"codigo":"380","nombre":"LA CAPILLA","codigodepartamento":"15"},
    {"codigo":"401","nombre":"LA VICTORIA","codigodepartamento":"15"},
    {"codigo":"403","nombre":"LA UVITA","codigodepartamento":"15"},
    {"codigo":"407","nombre":"VILLA DE LEYVA","codigodepartamento":"15"},
    {"codigo":"425","nombre":"MACANAL","codigodepartamento":"15"},
    {"codigo":"455","nombre":"MIRAFLORES","codigodepartamento":"15"},
    {"codigo":"464","nombre":"MONGUA","codigodepartamento":"15"},
    {"codigo":"466","nombre":"MONGUI","codigodepartamento":"15"},
    {"codigo":"469","nombre":"MONIQUIRA","codigodepartamento":"15"},
    {"codigo":"476","nombre":"MOTAVITA","codigodepartamento":"15"},
    {"codigo":"480","nombre":"MUZO","codigodepartamento":"15"},
    {"codigo":"491","nombre":"NOBSA","codigodepartamento":"15"},
    {"codigo":"494","nombre":"NUEVO COLON","codigodepartamento":"15"},
    {"codigo":"500","nombre":"OICATA","codigodepartamento":"15"},
    {"codigo":"507","nombre":"OTANCHE","codigodepartamento":"15"},
    {"codigo":"511","nombre":"PACHAVITA","codigodepartamento":"15"},
    {"codigo":"514","nombre":"PAEZ","codigodepartamento":"15"},
    {"codigo":"516","nombre":"PAIPA","codigodepartamento":"15"},
    {"codigo":"518","nombre":"PAJARITO","codigodepartamento":"15"},
    {"codigo":"522","nombre":"PANQUEBA","codigodepartamento":"15"},
    {"codigo":"531","nombre":"PAUNA","codigodepartamento":"15"},
    {"codigo":"533","nombre":"PAYA","codigodepartamento":"15"},
    {"codigo":"537","nombre":"PAZ DE RIO","codigodepartamento":"15"},
    {"codigo":"542","nombre":"PESCA","codigodepartamento":"15"},
    {"codigo":"550","nombre":"PISBA","codigodepartamento":"15"},
    {"codigo":"572","nombre":"PUERTO BOYACA","codigodepartamento":"15"},
    {"codigo":"580","nombre":"QUIPAMA","codigodepartamento":"15"},
    {"codigo":"599","nombre":"RAMIRIQUI","codigodepartamento":"15"},
    {"codigo":"600","nombre":"RAQUIRA","codigodepartamento":"15"},
    {"codigo":"621","nombre":"RONDON","codigodepartamento":"15"},
    {"codigo":"632","nombre":"SABOYA","codigodepartamento":"15"},
    {"codigo":"638","nombre":"SACHICA","codigodepartamento":"15"},
    {"codigo":"646","nombre":"SAMACA","codigodepartamento":"15"},
    {"codigo":"660","nombre":"SAN EDUARDO","codigodepartamento":"15"},
    {"codigo":"664","nombre":"SAN JOSE DE PARE","codigodepartamento":"15"},
    {"codigo":"667","nombre":"SAN LUIS DE GACENO","codigodepartamento":"15"},
    {"codigo":"673","nombre":"SAN MATEO","codigodepartamento":"15"},
    {"codigo":"676","nombre":"SAN MIGUEL DE SEMA","codigodepartamento":"15"},
    {"codigo":"681","nombre":"SAN PABLO BORBUR","codigodepartamento":"15"},
    {"codigo":"686","nombre":"SANTANA","codigodepartamento":"15"},
    {"codigo":"690","nombre":"SANTA MARIA","codigodepartamento":"15"},
    {"codigo":"693","nombre":"SAN ROSA VITERBO","codigodepartamento":"15"},
    {"codigo":"696","nombre":"SANTA SOFIA","codigodepartamento":"15"},
    {"codigo":"720","nombre":"SATIVANORTE","codigodepartamento":"15"},
    {"codigo":"723","nombre":"SATIVASUR","codigodepartamento":"15"},
    {"codigo":"740","nombre":"SIACHOQUE","codigodepartamento":"15"},
    {"codigo":"753","nombre":"SOATA","codigodepartamento":"15"},
    {"codigo":"755","nombre":"SOCOTA","codigodepartamento":"15"},
    {"codigo":"757","nombre":"SOCHA","codigodepartamento":"15"},
    {"codigo":"759","nombre":"SOGAMOSO","codigodepartamento":"15"},
    {"codigo":"761","nombre":"SOMONDOCO","codigodepartamento":"15"},
    {"codigo":"762","nombre":"SORA","codigodepartamento":"15"},
    {"codigo":"763","nombre":"SOTAQUIRA","codigodepartamento":"15"},
    {"codigo":"764","nombre":"SORACA","codigodepartamento":"15"},
    {"codigo":"774","nombre":"SUSACON","codigodepartamento":"15"},
    {"codigo":"776","nombre":"SUTAMARCHAN","codigodepartamento":"15"},
    {"codigo":"778","nombre":"SUTATENZA","codigodepartamento":"15"},
    {"codigo":"790","nombre":"TASCO","codigodepartamento":"15"},
    {"codigo":"798","nombre":"TENZA","codigodepartamento":"15"},
    {"codigo":"804","nombre":"TIBANA","codigodepartamento":"15"},
    {"codigo":"806","nombre":"TIBASOSA","codigodepartamento":"15"},
    {"codigo":"808","nombre":"TINJACA","codigodepartamento":"15"},
    {"codigo":"810","nombre":"TIPACOQUE","codigodepartamento":"15"},
    {"codigo":"814","nombre":"TOCA","codigodepartamento":"15"},
    {"codigo":"816","nombre":"TOGUI","codigodepartamento":"15"},
    {"codigo":"820","nombre":"TOPAGA","codigodepartamento":"15"},
    {"codigo":"822","nombre":"TOTA","codigodepartamento":"15"},
    {"codigo":"832","nombre":"TUNUNGUA","codigodepartamento":"15"},
    {"codigo":"835","nombre":"TURMEQUE","codigodepartamento":"15"},
    {"codigo":"837","nombre":"TUTA","codigodepartamento":"15"},
    {"codigo":"839","nombre":"TUTAZA","codigodepartamento":"15"},
    {"codigo":"842","nombre":"UMBITA","codigodepartamento":"15"},
    {"codigo":"861","nombre":"VENTAQUEMADA","codigodepartamento":"15"},
    {"codigo":"879","nombre":"VIRACACHA","codigodepartamento":"15"},
    {"codigo":"897","nombre":"ZETAQUIRA","codigodepartamento":"15"},
    {"codigo":"001","nombre":"MANIZALES","codigodepartamento":"17"},
    {"codigo":"01","nombre":"MANIZALES","codigodepartamento":"17"},
    {"codigo":"013","nombre":"AGUADAS","codigodepartamento":"17"},
    {"codigo":"02","nombre":"SUPIA","codigodepartamento":"17"},
    {"codigo":"03","nombre":"LA DORADA","codigodepartamento":"17"},
    {"codigo":"04","nombre":"CHINCHINA","codigodepartamento":"17"},
    {"codigo":"042","nombre":"ANSERMA","codigodepartamento":"17"},
    {"codigo":"05","nombre":"PENSILVANIA","codigodepartamento":"17"},
    {"codigo":"050","nombre":"ARANZAZU","codigodepartamento":"17"},
    {"codigo":"06","nombre":"RIOSUCIO","codigodepartamento":"17"},
    {"codigo":"07","nombre":"PALESTINA","codigodepartamento":"17"},
    {"codigo":"088","nombre":"BELALCAZAR","codigodepartamento":"17"},
    {"codigo":"174","nombre":"CHINCHINA","codigodepartamento":"17"},
    {"codigo":"272","nombre":"FILADELFIA","codigodepartamento":"17"},
    {"codigo":"380","nombre":"LA DORADA","codigodepartamento":"17"},
    {"codigo":"388","nombre":"LA MERCED","codigodepartamento":"17"},
    {"codigo":"433","nombre":"MANZANARES","codigodepartamento":"17"},
    {"codigo":"444","nombre":"MARQUETALIA","codigodepartamento":"17"},
    {"codigo":"446","nombre":"MARULANDA","codigodepartamento":"17"},
    {"codigo":"486","nombre":"NEIRA","codigodepartamento":"17"},
    {"codigo":"495","nombre":"NORCASIA","codigodepartamento":"17"},
    {"codigo":"513","nombre":"PACORA","codigodepartamento":"17"},
    {"codigo":"524","nombre":"PALESTINA","codigodepartamento":"17"},
    {"codigo":"541","nombre":"PENSILVANIA","codigodepartamento":"17"},
    {"codigo":"614","nombre":"RIOSUCIO","codigodepartamento":"17"},
    {"codigo":"616","nombre":"RISARALDA","codigodepartamento":"17"},
    {"codigo":"653","nombre":"SALAMINA","codigodepartamento":"17"},
    {"codigo":"662","nombre":"SAMANA","codigodepartamento":"17"},
    {"codigo":"665","nombre":"SAN JOSE","codigodepartamento":"17"},
    {"codigo":"777","nombre":"SUPIA","codigodepartamento":"17"},
    {"codigo":"867","nombre":"VICTORIA","codigodepartamento":"17"},
    {"codigo":"873","nombre":"VILLAMARIA","codigodepartamento":"17"},
    {"codigo":"877","nombre":"VITERBO","codigodepartamento":"17"},
    {"codigo":"001","nombre":"FLORENCIA","codigodepartamento":"18"},
    {"codigo":"029","nombre":"ALBANIA","codigodepartamento":"18"},
    {"codigo":"094","nombre":"BELEN DE LOS ANDAQUIES","codigodepartamento":"18"},
    {"codigo":"150","nombre":"CARTAGENA DEL CHAIRA","codigodepartamento":"18"},
    {"codigo":"205","nombre":"CURRILLO","codigodepartamento":"18"},
    {"codigo":"247","nombre":"EL DONCELLO","codigodepartamento":"18"},
    {"codigo":"256","nombre":"EL PAUJIL","codigodepartamento":"18"},
    {"codigo":"410","nombre":"LA MONTAÑITA","codigodepartamento":"18"},
    {"codigo":"460","nombre":"MILAN","codigodepartamento":"18"},
    {"codigo":"479","nombre":"MORELIA","codigodepartamento":"18"},
    {"codigo":"592","nombre":"PUERTO RICO","codigodepartamento":"18"},
    {"codigo":"610","nombre":"SAN JOSE DE LA FRAGUA","codigodepartamento":"18"},
    {"codigo":"753","nombre":"SAN VICENTE DEL CAGÜAN","codigodepartamento":"18"},
    {"codigo":"756","nombre":"SOLANO","codigodepartamento":"18"},
    {"codigo":"785","nombre":"SOLITA","codigodepartamento":"18"},
    {"codigo":"860","nombre":"VALPARAISO","codigodepartamento":"18"},
    {"codigo":"001","nombre":"POPAYAN","codigodepartamento":"19"},
    {"codigo":"022","nombre":"ALMAGUER","codigodepartamento":"19"},
    {"codigo":"050","nombre":"ARGELIA","codigodepartamento":"19"},
    {"codigo":"075","nombre":"BALBOA","codigodepartamento":"19"},
    {"codigo":"100","nombre":"BOLIVAR","codigodepartamento":"19"},
    {"codigo":"110","nombre":"BUENOS AIRES","codigodepartamento":"19"},
    {"codigo":"130","nombre":"CAJIBIO","codigodepartamento":"19"},
    {"codigo":"137","nombre":"CALDONO","codigodepartamento":"19"},
    {"codigo":"142","nombre":"CALOTO","codigodepartamento":"19"},
    {"codigo":"212","nombre":"CORINTO","codigodepartamento":"19"},
    {"codigo":"256","nombre":"EL TAMBO","codigodepartamento":"19"},
    {"codigo":"290","nombre":"FLORENCIA","codigodepartamento":"19"},
    {"codigo":"318","nombre":"GUAPI","codigodepartamento":"19"},
    {"codigo":"355","nombre":"INZA","codigodepartamento":"19"},
    {"codigo":"364","nombre":"JAMBALO","codigodepartamento":"19"},
    {"codigo":"392","nombre":"LA SIERRA","codigodepartamento":"19"},
    {"codigo":"397","nombre":"LA VEGA","codigodepartamento":"19"},
    {"codigo":"418","nombre":"LOPEZ","codigodepartamento":"19"},
    {"codigo":"450","nombre":"MERCADERES","codigodepartamento":"19"},
    {"codigo":"455","nombre":"MIRANDA","codigodepartamento":"19"},
    {"codigo":"473","nombre":"MORALES","codigodepartamento":"19"},
    {"codigo":"513","nombre":"PADILLA","codigodepartamento":"19"},
    {"codigo":"517","nombre":"PAEZ","codigodepartamento":"19"},
    {"codigo":"532","nombre":"PATIA","codigodepartamento":"19"},
    {"codigo":"533","nombre":"PIAMONTE","codigodepartamento":"19"},
    {"codigo":"548","nombre":"PIENDAMO","codigodepartamento":"19"},
    {"codigo":"573","nombre":"PUERTO TEJADA","codigodepartamento":"19"},
    {"codigo":"585","nombre":"PURACE","codigodepartamento":"19"},
    {"codigo":"622","nombre":"ROSAS","codigodepartamento":"19"},
    {"codigo":"693","nombre":"SAN SEBASTIAN","codigodepartamento":"19"},
    {"codigo":"698","nombre":"SANTANDER DE QUILICHAO","codigodepartamento":"19"},
    {"codigo":"701","nombre":"SANTA ROSA","codigodepartamento":"19"},
    {"codigo":"743","nombre":"SILVIA","codigodepartamento":"19"},
    {"codigo":"760","nombre":"SOTARA","codigodepartamento":"19"},
    {"codigo":"780","nombre":"SUAREZ","codigodepartamento":"19"},
    {"codigo":"785","nombre":"SUCRE","codigodepartamento":"19"},
    {"codigo":"807","nombre":"TIMBIO","codigodepartamento":"19"},
    {"codigo":"809","nombre":"TIMBIQUI","codigodepartamento":"19"},
    {"codigo":"821","nombre":"TORIBIO","codigodepartamento":"19"},
    {"codigo":"824","nombre":"TOTORO","codigodepartamento":"19"},
    {"codigo":"845","nombre":"VILLA RICA","codigodepartamento":"19"},
    {"codigo":"001","nombre":"VALLEDUPAR","codigodepartamento":"20"},
    {"codigo":"011","nombre":"AGUACHICA","codigodepartamento":"20"},
    {"codigo":"013","nombre":"AGUSTIN CODAZZI","codigodepartamento":"20"},
    {"codigo":"032","nombre":"ASTREA","codigodepartamento":"20"},
    {"codigo":"045","nombre":"BECERRIL","codigodepartamento":"20"},
    {"codigo":"060","nombre":"BOSCONIA","codigodepartamento":"20"},
    {"codigo":"175","nombre":"CHIMICHAGUA","codigodepartamento":"20"},
    {"codigo":"178","nombre":"CHIRIGUANA","codigodepartamento":"20"},
    {"codigo":"228","nombre":"CURUMANI","codigodepartamento":"20"},
    {"codigo":"238","nombre":"EL COPEY","codigodepartamento":"20"},
    {"codigo":"250","nombre":"EL PASO","codigodepartamento":"20"},
    {"codigo":"295","nombre":"GAMARRA","codigodepartamento":"20"},
    {"codigo":"310","nombre":"GONZALEZ","codigodepartamento":"20"},
    {"codigo":"383","nombre":"LA GLORIA","codigodepartamento":"20"},
    {"codigo":"400","nombre":"LA JAGUA DE IBIRICO","codigodepartamento":"20"},
    {"codigo":"443","nombre":"MANAURE","codigodepartamento":"20"},
    {"codigo":"517","nombre":"PAILITAS","codigodepartamento":"20"},
    {"codigo":"550","nombre":"PELAYA","codigodepartamento":"20"},
    {"codigo":"570","nombre":"PUEBLO BELLO","codigodepartamento":"20"},
    {"codigo":"614","nombre":"RIO DE ORO","codigodepartamento":"20"},
    {"codigo":"621","nombre":"LA PAZ","codigodepartamento":"20"},
    {"codigo":"710","nombre":"SAN ALBERTO","codigodepartamento":"20"},
    {"codigo":"750","nombre":"SAN DIEGO","codigodepartamento":"20"},
    {"codigo":"770","nombre":"SAN MARTIN","codigodepartamento":"20"},
    {"codigo":"787","nombre":"TAMALAMEQUE","codigodepartamento":"20"},
    {"codigo":"001","nombre":"MONTERIA","codigodepartamento":"23"},
    {"codigo":"068","nombre":"AYAPEL","codigodepartamento":"23"},
    {"codigo":"079","nombre":"BUENAVISTA","codigodepartamento":"23"},
    {"codigo":"090","nombre":"CANALETE","codigodepartamento":"23"},
    {"codigo":"162","nombre":"CERETE","codigodepartamento":"23"},
    {"codigo":"168","nombre":"CHIMA","codigodepartamento":"23"},
    {"codigo":"182","nombre":"CHINU","codigodepartamento":"23"},
    {"codigo":"189","nombre":"CIENAGA DE ORO","codigodepartamento":"23"},
    {"codigo":"300","nombre":"COTORRA","codigodepartamento":"23"},
    {"codigo":"350","nombre":"LA APARTADA","codigodepartamento":"23"},
    {"codigo":"417","nombre":"LORICA","codigodepartamento":"23"},
    {"codigo":"419","nombre":"LOS CORDOBAS","codigodepartamento":"23"},
    {"codigo":"464","nombre":"MOMIL","codigodepartamento":"23"},
    {"codigo":"466","nombre":"MONTELIBANO","codigodepartamento":"23"},
    {"codigo":"500","nombre":"MOÑITOS","codigodepartamento":"23"},
    {"codigo":"555","nombre":"PLANETA RICA","codigodepartamento":"23"},
    {"codigo":"570","nombre":"PUEBLO NUEVO","codigodepartamento":"23"},
    {"codigo":"574","nombre":"PUERTO ESCONDIDO","codigodepartamento":"23"},
    {"codigo":"580","nombre":"PUERTO LIBERTADOR","codigodepartamento":"23"},
    {"codigo":"586","nombre":"PURISIMA","codigodepartamento":"23"},
    {"codigo":"660","nombre":"SAHAGUN","codigodepartamento":"23"},
    {"codigo":"670","nombre":"SAN ANDRES DE SOTAVENTO","codigodepartamento":"23"},
    {"codigo":"672","nombre":"SAN ANTERO","codigodepartamento":"23"},
    {"codigo":"675","nombre":"SAN BERNARDO DEL VIENTO","codigodepartamento":"23"},
    {"codigo":"678","nombre":"SAN CARLOS","codigodepartamento":"23"},
    {"codigo":"686","nombre":"SAN PELAYO","codigodepartamento":"23"},
    {"codigo":"807","nombre":"TIERRALTA","codigodepartamento":"23"},
    {"codigo":"855","nombre":"VALENCIA","codigodepartamento":"23"},
    {"codigo":"001","nombre":"AGUA DE DIOS","codigodepartamento":"25"},
    {"codigo":"019","nombre":"ALBAN","codigodepartamento":"25"},
    {"codigo":"035","nombre":"ANAPOIMA","codigodepartamento":"25"},
    {"codigo":"040","nombre":"ANOLAIMA","codigodepartamento":"25"},
    {"codigo":"053","nombre":"ARBELAEZ","codigodepartamento":"25"},
    {"codigo":"086","nombre":"BELTRAN","codigodepartamento":"25"},
    {"codigo":"095","nombre":"BITUIMA","codigodepartamento":"25"},
    {"codigo":"099","nombre":"BOJACA","codigodepartamento":"25"},
    {"codigo":"120","nombre":"CABRERA","codigodepartamento":"25"},
    {"codigo":"123","nombre":"CACHIPAY","codigodepartamento":"25"},
    {"codigo":"126","nombre":"CAJICA","codigodepartamento":"25"},
    {"codigo":"148","nombre":"CAPARRAPI","codigodepartamento":"25"},
    {"codigo":"151","nombre":"CAQUEZA","codigodepartamento":"25"},
    {"codigo":"154","nombre":"CARMEN DE CARUPA","codigodepartamento":"25"},
    {"codigo":"168","nombre":"CHAGUANI","codigodepartamento":"25"},
    {"codigo":"175","nombre":"CHIA","codigodepartamento":"25"},
    {"codigo":"178","nombre":"CHIPAQUE","codigodepartamento":"25"},
    {"codigo":"181","nombre":"CHOACHI","codigodepartamento":"25"},
    {"codigo":"183","nombre":"CHOCONTA","codigodepartamento":"25"},
    {"codigo":"200","nombre":"COGUA","codigodepartamento":"25"},
    {"codigo":"214","nombre":"COTA","codigodepartamento":"25"},
    {"codigo":"224","nombre":"CUCUNUBA","codigodepartamento":"25"},
    {"codigo":"245","nombre":"EL COLEGIO","codigodepartamento":"25"},
    {"codigo":"258","nombre":"EL PEÑON","codigodepartamento":"25"},
    {"codigo":"260","nombre":"EL ROSAL","codigodepartamento":"25"},
    {"codigo":"269","nombre":"FACATATIVA","codigodepartamento":"25"},
    {"codigo":"279","nombre":"FOMEQUE","codigodepartamento":"25"},
    {"codigo":"281","nombre":"FOSCA","codigodepartamento":"25"},
    {"codigo":"286","nombre":"FUNZA","codigodepartamento":"25"},
    {"codigo":"288","nombre":"FUQUENE","codigodepartamento":"25"},
    {"codigo":"290","nombre":"FUSAGASUGA","codigodepartamento":"25"},
    {"codigo":"293","nombre":"GACHALA","codigodepartamento":"25"},
    {"codigo":"295","nombre":"GACHANCIPA","codigodepartamento":"25"},
    {"codigo":"297","nombre":"GACHETA","codigodepartamento":"25"},
    {"codigo":"299","nombre":"GAMA","codigodepartamento":"25"},
    {"codigo":"307","nombre":"GIRARDOT","codigodepartamento":"25"},
    {"codigo":"312","nombre":"GRANADA","codigodepartamento":"25"},
    {"codigo":"317","nombre":"GUACHETA","codigodepartamento":"25"},
    {"codigo":"320","nombre":"GUADUAS","codigodepartamento":"25"},
    {"codigo":"322","nombre":"GUASCA","codigodepartamento":"25"},
    {"codigo":"324","nombre":"GUATAQUI","codigodepartamento":"25"},
    {"codigo":"326","nombre":"GUATAVITA","codigodepartamento":"25"},
    {"codigo":"328","nombre":"GUAYABAL DE SIQUIMA","codigodepartamento":"25"},
    {"codigo":"335","nombre":"GUAYABETAL","codigodepartamento":"25"},
    {"codigo":"339","nombre":"GUTIERREZ","codigodepartamento":"25"},
    {"codigo":"368","nombre":"JERUSALEN","codigodepartamento":"25"},
    {"codigo":"372","nombre":"JUNIN","codigodepartamento":"25"},
    {"codigo":"377","nombre":"LA CALERA","codigodepartamento":"25"},
    {"codigo":"386","nombre":"LA MESA","codigodepartamento":"25"},
    {"codigo":"394","nombre":"LA PALMA","codigodepartamento":"25"},
    {"codigo":"398","nombre":"LA PEÑA","codigodepartamento":"25"},
    {"codigo":"402","nombre":"LA VEGA","codigodepartamento":"25"},
    {"codigo":"407","nombre":"LENGUAZAQUE","codigodepartamento":"25"},
    {"codigo":"426","nombre":"MACHETA","codigodepartamento":"25"},
    {"codigo":"430","nombre":"MADRID","codigodepartamento":"25"},
    {"codigo":"436","nombre":"MANTA","codigodepartamento":"25"},
    {"codigo":"438","nombre":"MEDINA","codigodepartamento":"25"},
    {"codigo":"473","nombre":"MOSQUERA","codigodepartamento":"25"},
    {"codigo":"483","nombre":"NARIÑO","codigodepartamento":"25"},
    {"codigo":"486","nombre":"NEMOCON","codigodepartamento":"25"},
    {"codigo":"488","nombre":"NILO","codigodepartamento":"25"},
    {"codigo":"489","nombre":"NIMAIMA","codigodepartamento":"25"},
    {"codigo":"491","nombre":"NOCAIMA","codigodepartamento":"25"},
    {"codigo":"506","nombre":"VENECIA","codigodepartamento":"25"},
    {"codigo":"513","nombre":"PACHO","codigodepartamento":"25"},
    {"codigo":"518","nombre":"PAIME","codigodepartamento":"25"},
    {"codigo":"524","nombre":"PANDI","codigodepartamento":"25"},
    {"codigo":"530","nombre":"PARATEBUENO","codigodepartamento":"25"},
    {"codigo":"535","nombre":"PASCA","codigodepartamento":"25"},
    {"codigo":"572","nombre":"PUERTO SALGAR","codigodepartamento":"25"},
    {"codigo":"580","nombre":"PULI","codigodepartamento":"25"},
    {"codigo":"592","nombre":"QUEBRADANEGRA","codigodepartamento":"25"},
    {"codigo":"594","nombre":"QUETAME","codigodepartamento":"25"},
    {"codigo":"596","nombre":"QUIPILE","codigodepartamento":"25"},
    {"codigo":"599","nombre":"APULO","codigodepartamento":"25"},
    {"codigo":"612","nombre":"RICAURTE","codigodepartamento":"25"},
    {"codigo":"645","nombre":"SAN ANTONIO DE TEQUENDAMA","codigodepartamento":"25"},
    {"codigo":"649","nombre":"SAN BERNARDO","codigodepartamento":"25"},
    {"codigo":"653","nombre":"SAN CAYETANO","codigodepartamento":"25"},
    {"codigo":"658","nombre":"SAN FRANCISCO","codigodepartamento":"25"},
    {"codigo":"662","nombre":"SAN JUAN DE RIOSECO","codigodepartamento":"25"},
    {"codigo":"718","nombre":"SASAIMA","codigodepartamento":"25"},
    {"codigo":"736","nombre":"SESQUILE","codigodepartamento":"25"},
    {"codigo":"740","nombre":"SIBATE","codigodepartamento":"25"},
    {"codigo":"743","nombre":"SILVANIA","codigodepartamento":"25"},
    {"codigo":"745","nombre":"SIMIJACA","codigodepartamento":"25"},
    {"codigo":"754","nombre":"SOACHA","codigodepartamento":"25"},
    {"codigo":"758","nombre":"SOPO","codigodepartamento":"25"},
    {"codigo":"769","nombre":"SUBACHOQUE","codigodepartamento":"25"},
    {"codigo":"772","nombre":"SUESCA","codigodepartamento":"25"},
    {"codigo":"777","nombre":"SUPATA","codigodepartamento":"25"},
    {"codigo":"779","nombre":"SUSA","codigodepartamento":"25"},
    {"codigo":"781","nombre":"SUTATAUSA","codigodepartamento":"25"},
    {"codigo":"785","nombre":"TABIO","codigodepartamento":"25"},
    {"codigo":"793","nombre":"TAUSA","codigodepartamento":"25"},
    {"codigo":"797","nombre":"TENA","codigodepartamento":"25"},
    {"codigo":"799","nombre":"TENJO","codigodepartamento":"25"},
    {"codigo":"805","nombre":"TIBACUY","codigodepartamento":"25"},
    {"codigo":"807","nombre":"TIBIRITA","codigodepartamento":"25"},
    {"codigo":"815","nombre":"TOCAIMA","codigodepartamento":"25"},
    {"codigo":"817","nombre":"TOCANCIPA","codigodepartamento":"25"},
    {"codigo":"823","nombre":"TOPAIPI","codigodepartamento":"25"},
    {"codigo":"839","nombre":"UBALA","codigodepartamento":"25"},
    {"codigo":"841","nombre":"UBAQUE","codigodepartamento":"25"},
    {"codigo":"843","nombre":"UBATE","codigodepartamento":"25"},
    {"codigo":"845","nombre":"UNE","codigodepartamento":"25"},
    {"codigo":"851","nombre":"UTICA","codigodepartamento":"25"},
    {"codigo":"862","nombre":"VERGARA","codigodepartamento":"25"},
    {"codigo":"867","nombre":"VIANI","codigodepartamento":"25"},
    {"codigo":"871","nombre":"VILLAGOMEZ","codigodepartamento":"25"},
    {"codigo":"873","nombre":"VILLAPINZON","codigodepartamento":"25"},
    {"codigo":"875","nombre":"VILLETA","codigodepartamento":"25"},
    {"codigo":"878","nombre":"VIOTA","codigodepartamento":"25"},
    {"codigo":"885","nombre":"YACOPI","codigodepartamento":"25"},
    {"codigo":"898","nombre":"ZIPACON","codigodepartamento":"25"},
    {"codigo":"899","nombre":"ZIPAQUIRA","codigodepartamento":"25"},
    {"codigo":"001","nombre":"QUIBDO","codigodepartamento":"27"},
    {"codigo":"006","nombre":"ACANDI","codigodepartamento":"27"},
    {"codigo":"025","nombre":"ALTO BAUDO","codigodepartamento":"27"},
    {"codigo":"050","nombre":"ATRATO","codigodepartamento":"27"},
    {"codigo":"073","nombre":"BAGADO","codigodepartamento":"27"},
    {"codigo":"075","nombre":"BAHIA SOLANO","codigodepartamento":"27"},
    {"codigo":"077","nombre":"BAJO BAUDO","codigodepartamento":"27"},
    {"codigo":"086","nombre":"BLEN DE BAJIRA","codigodepartamento":"27"},
    {"codigo":"099","nombre":"BOJAYA","codigodepartamento":"27"},
    {"codigo":"135","nombre":"CANTON DE SAN PABLO","codigodepartamento":"27"},
    {"codigo":"150","nombre":"CARMEN DEL DARIEN","codigodepartamento":"27"},
    {"codigo":"160","nombre":"CERTEGUI","codigodepartamento":"27"},
    {"codigo":"205","nombre":"CONDOTO","codigodepartamento":"27"},
    {"codigo":"245","nombre":"EL CARMEN DE ATRATO","codigodepartamento":"27"},
    {"codigo":"250","nombre":"EL LITORAL DEL SAN JUAN","codigodepartamento":"27"},
    {"codigo":"361","nombre":"ITSMINA","codigodepartamento":"27"},
    {"codigo":"372","nombre":"JURADO","codigodepartamento":"27"},
    {"codigo":"413","nombre":"LLORO","codigodepartamento":"27"},
    {"codigo":"425","nombre":"MEDIO ATRATO","codigodepartamento":"27"},
    {"codigo":"430","nombre":"MEDIO BAUDO","codigodepartamento":"27"},
    {"codigo":"450","nombre":"MEDIO SAN JUAN","codigodepartamento":"27"},
    {"codigo":"491","nombre":"NOVITA","codigodepartamento":"27"},
    {"codigo":"495","nombre":"NUQUI","codigodepartamento":"27"},
    {"codigo":"580","nombre":"RIO IRO","codigodepartamento":"27"},
    {"codigo":"600","nombre":"RIO QUITO","codigodepartamento":"27"},
    {"codigo":"615","nombre":"RIOSUCIO","codigodepartamento":"27"},
    {"codigo":"660","nombre":"SAN JOSE DEL PALMAR","codigodepartamento":"27"},
    {"codigo":"745","nombre":"SIPI","codigodepartamento":"27"},
    {"codigo":"787","nombre":"TADO","codigodepartamento":"27"},
    {"codigo":"800","nombre":"UNGUIA","codigodepartamento":"27"},
    {"codigo":"810","nombre":"UNION PANAMERICANA","codigodepartamento":"27"},
    {"codigo":"001","nombre":"NEIVA","codigodepartamento":"41"},
    {"codigo":"006","nombre":"ACEVEDO","codigodepartamento":"41"},
    {"codigo":"013","nombre":"AGRADO","codigodepartamento":"41"},
    {"codigo":"016","nombre":"AIPE","codigodepartamento":"41"},
    {"codigo":"020","nombre":"ALGECIRAS","codigodepartamento":"41"},
    {"codigo":"026","nombre":"ALTAMIRA","codigodepartamento":"41"},
    {"codigo":"078","nombre":"BARAYA","codigodepartamento":"41"},
    {"codigo":"132","nombre":"CAMPOALEGRE","codigodepartamento":"41"},
    {"codigo":"206","nombre":"COLOMBIA","codigodepartamento":"41"},
    {"codigo":"244","nombre":"ELIAS","codigodepartamento":"41"},
    {"codigo":"298","nombre":"GARZON","codigodepartamento":"41"},
    {"codigo":"306","nombre":"GIGANTE","codigodepartamento":"41"},
    {"codigo":"319","nombre":"GUADALUPE","codigodepartamento":"41"},
    {"codigo":"349","nombre":"HOBO","codigodepartamento":"41"},
    {"codigo":"357","nombre":"IQUIRA","codigodepartamento":"41"},
    {"codigo":"359","nombre":"ISNOS","codigodepartamento":"41"},
    {"codigo":"378","nombre":"LA ARGENTINA","codigodepartamento":"41"},
    {"codigo":"396","nombre":"LA PLATA","codigodepartamento":"41"},
    {"codigo":"483","nombre":"NATAGA","codigodepartamento":"41"},
    {"codigo":"503","nombre":"OPORAPA","codigodepartamento":"41"},
    {"codigo":"518","nombre":"PAICOL","codigodepartamento":"41"},
    {"codigo":"524","nombre":"PALERMO","codigodepartamento":"41"},
    {"codigo":"530","nombre":"PALESTINA","codigodepartamento":"41"},
    {"codigo":"548","nombre":"PITAL","codigodepartamento":"41"},
    {"codigo":"551","nombre":"PITALITO","codigodepartamento":"41"},
    {"codigo":"615","nombre":"RIVERA","codigodepartamento":"41"},
    {"codigo":"660","nombre":"SALADOBLANCO","codigodepartamento":"41"},
    {"codigo":"668","nombre":"SAN AGUSTIN","codigodepartamento":"41"},
    {"codigo":"676","nombre":"SANTA MARIA","codigodepartamento":"41"},
    {"codigo":"770","nombre":"SUAZA","codigodepartamento":"41"},
    {"codigo":"791","nombre":"TARQUI","codigodepartamento":"41"},
    {"codigo":"797","nombre":"TESALIA","codigodepartamento":"41"},
    {"codigo":"799","nombre":"TELLO","codigodepartamento":"41"},
    {"codigo":"801","nombre":"TERUEL","codigodepartamento":"41"},
    {"codigo":"807","nombre":"TIMANA","codigodepartamento":"41"},
    {"codigo":"872","nombre":"VILLAVIEJA","codigodepartamento":"41"},
    {"codigo":"885","nombre":"YAGUARA","codigodepartamento":"41"},
    {"codigo":"001","nombre":"RIOHACHA","codigodepartamento":"44"},
    {"codigo":"035","nombre":"ALBANIA","codigodepartamento":"44"},
    {"codigo":"078","nombre":"BARRANCAS","codigodepartamento":"44"},
    {"codigo":"090","nombre":"DIBULLA","codigodepartamento":"44"},
    {"codigo":"098","nombre":"DISTRACCION","codigodepartamento":"44"},
    {"codigo":"110","nombre":"EL MOLINO","codigodepartamento":"44"},
    {"codigo":"279","nombre":"FONSECA","codigodepartamento":"44"},
    {"codigo":"378","nombre":"HATONUEVO","codigodepartamento":"44"},
    {"codigo":"420","nombre":"LA JAGUA DEL PILAR","codigodepartamento":"44"},
    {"codigo":"430","nombre":"MAICAO","codigodepartamento":"44"},
    {"codigo":"560","nombre":"MANAURE","codigodepartamento":"44"},
    {"codigo":"650","nombre":"SAN JUAN DEL CESAR","codigodepartamento":"44"},
    {"codigo":"847","nombre":"URIBIA","codigodepartamento":"44"},
    {"codigo":"855","nombre":"URUMITA","codigodepartamento":"44"},
    {"codigo":"874","nombre":"VILLANUEVA","codigodepartamento":"44"},
    {"codigo":"001","nombre":"SANTA MARTA","codigodepartamento":"47"},
    {"codigo":"030","nombre":"ALGARROBO","codigodepartamento":"47"},
    {"codigo":"053","nombre":"ARACATACA","codigodepartamento":"47"},
    {"codigo":"058","nombre":"ARIGUANI","codigodepartamento":"47"},
    {"codigo":"161","nombre":"CERRO SAN ANTONIO","codigodepartamento":"47"},
    {"codigo":"170","nombre":"CHIVOLO","codigodepartamento":"47"},
    {"codigo":"189","nombre":"CIENAGA","codigodepartamento":"47"},
    {"codigo":"205","nombre":"CONCORDIA","codigodepartamento":"47"},
    {"codigo":"245","nombre":"EL BANCO","codigodepartamento":"47"},
    {"codigo":"258","nombre":"EL PIÑON","codigodepartamento":"47"},
    {"codigo":"268","nombre":"EL RETEN","codigodepartamento":"47"},
    {"codigo":"288","nombre":"FUNDACION","codigodepartamento":"47"},
    {"codigo":"318","nombre":"GUAMAL","codigodepartamento":"47"},
    {"codigo":"460","nombre":"NUEVA GRANADA","codigodepartamento":"47"},
    {"codigo":"541","nombre":"PEDRAZA","codigodepartamento":"47"},
    {"codigo":"545","nombre":"PIJINO DEL CARMEN","codigodepartamento":"47"},
    {"codigo":"551","nombre":"PIVIJAY","codigodepartamento":"47"},
    {"codigo":"555","nombre":"PLATO","codigodepartamento":"47"},
    {"codigo":"570","nombre":"PUEBLOVIEJO","codigodepartamento":"47"},
    {"codigo":"605","nombre":"REMOLINO","codigodepartamento":"47"},
    {"codigo":"660","nombre":"SABANAS DE SAN ANGEL","codigodepartamento":"47"},
    {"codigo":"675","nombre":"SALAMINA","codigodepartamento":"47"},
    {"codigo":"692","nombre":"SAN SEBASTIAN DE BUENAVISTA","codigodepartamento":"47"},
    {"codigo":"703","nombre":"SAN ZENON","codigodepartamento":"47"},
    {"codigo":"707","nombre":"SANTA ANA","codigodepartamento":"47"},
    {"codigo":"720","nombre":"SANTA BARBARA DE PINTO","codigodepartamento":"47"},
    {"codigo":"745","nombre":"SITIONUEVO","codigodepartamento":"47"},
    {"codigo":"798","nombre":"TENERIFE","codigodepartamento":"47"},
    {"codigo":"960","nombre":"ZAPAYAN","codigodepartamento":"47"},
    {"codigo":"980","nombre":"ZONA BANANERA","codigodepartamento":"47"},
    {"codigo":"001","nombre":"VILLAVICENCIO","codigodepartamento":"50"},
    {"codigo":"006","nombre":"ACACIAS","codigodepartamento":"50"},
    {"codigo":"110","nombre":"BARRANCA DE UPIA","codigodepartamento":"50"},
    {"codigo":"124","nombre":"CABUYARO","codigodepartamento":"50"},
    {"codigo":"150","nombre":"CASTILLA LA NUEVA","codigodepartamento":"50"},
    {"codigo":"223","nombre":"SAN LUIS DE CUBARRAL","codigodepartamento":"50"},
    {"codigo":"226","nombre":"CUMARAL","codigodepartamento":"50"},
    {"codigo":"245","nombre":"EL CALVARIO","codigodepartamento":"50"},
    {"codigo":"251","nombre":"EL CASTILLO","codigodepartamento":"50"},
    {"codigo":"270","nombre":"EL DORADO","codigodepartamento":"50"},
    {"codigo":"287","nombre":"FUENTE DE ORO","codigodepartamento":"50"},
    {"codigo":"313","nombre":"GRANADA","codigodepartamento":"50"},
    {"codigo":"318","nombre":"GUAMAL","codigodepartamento":"50"},
    {"codigo":"325","nombre":"MAPIRIPAN","codigodepartamento":"50"},
    {"codigo":"330","nombre":"MESETAS","codigodepartamento":"50"},
    {"codigo":"350","nombre":"LA MACARENA","codigodepartamento":"50"},
    {"codigo":"370","nombre":"LA URIBE","codigodepartamento":"50"},
    {"codigo":"400","nombre":"LEJANIAS","codigodepartamento":"50"},
    {"codigo":"450","nombre":"PUERTO CONCORDIA","codigodepartamento":"50"},
    {"codigo":"568","nombre":"PUERTO GAITAN","codigodepartamento":"50"},
    {"codigo":"573","nombre":"PUERTO LOPEZ","codigodepartamento":"50"},
    {"codigo":"577","nombre":"PUERTO LLERAS","codigodepartamento":"50"},
    {"codigo":"590","nombre":"PUERTO RICO","codigodepartamento":"50"},
    {"codigo":"606","nombre":"RESTREPO","codigodepartamento":"50"},
    {"codigo":"680","nombre":"SAN CARLOS GUAROA","codigodepartamento":"50"},
    {"codigo":"683","nombre":"SAN JUAN DE ARAMA","codigodepartamento":"50"},
    {"codigo":"686","nombre":"SAN JUANITO","codigodepartamento":"50"},
    {"codigo":"689","nombre":"SAN MARTIN","codigodepartamento":"50"},
    {"codigo":"711","nombre":"VISTA HERMOSA","codigodepartamento":"50"},
    {"codigo":"001","nombre":"PASTO","codigodepartamento":"52"},
    {"codigo":"019","nombre":"ALBAN","codigodepartamento":"52"},
    {"codigo":"022","nombre":"ALDANA","codigodepartamento":"52"},
    {"codigo":"036","nombre":"ANCUYA","codigodepartamento":"52"},
    {"codigo":"051","nombre":"ARBOLEDA","codigodepartamento":"52"},
    {"codigo":"079","nombre":"BARBACOAS","codigodepartamento":"52"},
    {"codigo":"083","nombre":"BELEN","codigodepartamento":"52"},
    {"codigo":"110","nombre":"BUESACO","codigodepartamento":"52"},
    {"codigo":"203","nombre":"COLON","codigodepartamento":"52"},
    {"codigo":"207","nombre":"CONSACA","codigodepartamento":"52"},
    {"codigo":"210","nombre":"CONTADERO","codigodepartamento":"52"},
    {"codigo":"215","nombre":"CORDOBA","codigodepartamento":"52"},
    {"codigo":"224","nombre":"CUASPUD","codigodepartamento":"52"},
    {"codigo":"227","nombre":"CUMBAL","codigodepartamento":"52"},
    {"codigo":"233","nombre":"CUMBITARA","codigodepartamento":"52"},
    {"codigo":"240","nombre":"CHACHAGÜI","codigodepartamento":"52"},
    {"codigo":"250","nombre":"EL CHARCO","codigodepartamento":"52"},
    {"codigo":"254","nombre":"EL PENOL","codigodepartamento":"52"},
    {"codigo":"256","nombre":"EL ROSARIO","codigodepartamento":"52"},
    {"codigo":"258","nombre":"EL TABLÓN DE GÓMEZ","codigodepartamento":"52"},
    {"codigo":"260","nombre":"EL TAMBO","codigodepartamento":"52"},
    {"codigo":"287","nombre":"FUNES","codigodepartamento":"52"},
    {"codigo":"317","nombre":"GUACHUCAL","codigodepartamento":"52"},
    {"codigo":"320","nombre":"GUAITARILLA","codigodepartamento":"52"},
    {"codigo":"323","nombre":"GUALMATAN","codigodepartamento":"52"},
    {"codigo":"352","nombre":"ILES","codigodepartamento":"52"},
    {"codigo":"354","nombre":"IMUES","codigodepartamento":"52"},
    {"codigo":"356","nombre":"IPIALES","codigodepartamento":"52"},
    {"codigo":"378","nombre":"LA CRUZ","codigodepartamento":"52"},
    {"codigo":"381","nombre":"LA FLORIDA","codigodepartamento":"52"},
    {"codigo":"385","nombre":"LA LLANADA","codigodepartamento":"52"},
    {"codigo":"390","nombre":"LA TOLA","codigodepartamento":"52"},
    {"codigo":"399","nombre":"LA UNION","codigodepartamento":"52"},
    {"codigo":"405","nombre":"LEIVA","codigodepartamento":"52"},
    {"codigo":"411","nombre":"LINARES","codigodepartamento":"52"},
    {"codigo":"418","nombre":"LOS ANDES","codigodepartamento":"52"},
    {"codigo":"427","nombre":"MAGUI","codigodepartamento":"52"},
    {"codigo":"435","nombre":"MALLAMA","codigodepartamento":"52"},
    {"codigo":"473","nombre":"MOSQUERA","codigodepartamento":"52"},
    {"codigo":"480","nombre":"NARINO","codigodepartamento":"52"},
    {"codigo":"490","nombre":"OLAYA HERRERA","codigodepartamento":"52"},
    {"codigo":"506","nombre":"OSPINA","codigodepartamento":"52"},
    {"codigo":"520","nombre":"FRANCISCO PIZARRO","codigodepartamento":"52"},
    {"codigo":"540","nombre":"POLICARPA","codigodepartamento":"52"},
    {"codigo":"560","nombre":"POTOSI","codigodepartamento":"52"},
    {"codigo":"565","nombre":"PROVIDENCIA","codigodepartamento":"52"},
    {"codigo":"573","nombre":"PUERRES","codigodepartamento":"52"},
    {"codigo":"585","nombre":"PUPIALES","codigodepartamento":"52"},
    {"codigo":"612","nombre":"RICAURTE","codigodepartamento":"52"},
    {"codigo":"621","nombre":"ROBERTO PAYAN","codigodepartamento":"52"},
    {"codigo":"678","nombre":"SAMANIEGO","codigodepartamento":"52"},
    {"codigo":"683","nombre":"SANDONA","codigodepartamento":"52"},
    {"codigo":"685","nombre":"SAN BERNARDO","codigodepartamento":"52"},
    {"codigo":"687","nombre":"SAN LORENZO","codigodepartamento":"52"},
    {"codigo":"693","nombre":"SAN PABLO","codigodepartamento":"52"},
    {"codigo":"694","nombre":"SAN PEDRO DE CARTAGO","codigodepartamento":"52"},
    {"codigo":"696","nombre":"SANTA BARBARA","codigodepartamento":"52"},
    {"codigo":"699","nombre":"SANTACRUZ","codigodepartamento":"52"},
    {"codigo":"720","nombre":"SAPUYES","codigodepartamento":"52"},
    {"codigo":"786","nombre":"TAMINANGO","codigodepartamento":"52"},
    {"codigo":"788","nombre":"TANGUA","codigodepartamento":"52"},
    {"codigo":"835","nombre":"TUMACO","codigodepartamento":"52"},
    {"codigo":"838","nombre":"TUQUERRES","codigodepartamento":"52"},
    {"codigo":"885","nombre":"YACUANQUER","codigodepartamento":"52"},
    {"codigo":"001","nombre":"CUCUTA","codigodepartamento":"54"},
    {"codigo":"003","nombre":"ABREGO","codigodepartamento":"54"},
    {"codigo":"051","nombre":"ARBOLEDAS","codigodepartamento":"54"},
    {"codigo":"099","nombre":"BOCHALEMA","codigodepartamento":"54"},
    {"codigo":"109","nombre":"BUCARASICA","codigodepartamento":"54"},
    {"codigo":"125","nombre":"CACOTA","codigodepartamento":"54"},
    {"codigo":"128","nombre":"CACHIRA","codigodepartamento":"54"},
    {"codigo":"172","nombre":"CHINACOTA","codigodepartamento":"54"},
    {"codigo":"174","nombre":"CHITAGA","codigodepartamento":"54"},
    {"codigo":"206","nombre":"CONVENCION","codigodepartamento":"54"},
    {"codigo":"223","nombre":"CUCUTILLA","codigodepartamento":"54"},
    {"codigo":"239","nombre":"DURANIA","codigodepartamento":"54"},
    {"codigo":"245","nombre":"EL CARMEN","codigodepartamento":"54"},
    {"codigo":"250","nombre":"EL TARRA","codigodepartamento":"54"},
    {"codigo":"261","nombre":"EL ZULIA","codigodepartamento":"54"},
    {"codigo":"313","nombre":"GRAMALOTE","codigodepartamento":"54"},
    {"codigo":"344","nombre":"HACARI","codigodepartamento":"54"},
    {"codigo":"347","nombre":"HERRAN","codigodepartamento":"54"},
    {"codigo":"377","nombre":"LABATECA","codigodepartamento":"54"},
    {"codigo":"385","nombre":"LA ESPERANZA","codigodepartamento":"54"},
    {"codigo":"398","nombre":"LA PLAYA","codigodepartamento":"54"},
    {"codigo":"405","nombre":"LOS PATIOS","codigodepartamento":"54"},
    {"codigo":"418","nombre":"LOURDES","codigodepartamento":"54"},
    {"codigo":"480","nombre":"MUTISCUA","codigodepartamento":"54"},
    {"codigo":"498","nombre":"OCAÑA","codigodepartamento":"54"},
    {"codigo":"518","nombre":"PAMPLONA","codigodepartamento":"54"},
    {"codigo":"520","nombre":"PAMPLONITA","codigodepartamento":"54"},
    {"codigo":"553","nombre":"PUERTO SANTANDER","codigodepartamento":"54"},
    {"codigo":"599","nombre":"RAGONVALIA","codigodepartamento":"54"},
    {"codigo":"660","nombre":"SALAZAR","codigodepartamento":"54"},
    {"codigo":"670","nombre":"SAN CALIXTO","codigodepartamento":"54"},
    {"codigo":"673","nombre":"SAN CAYETANO","codigodepartamento":"54"},
    {"codigo":"680","nombre":"SANTIAGO","codigodepartamento":"54"},
    {"codigo":"720","nombre":"SARDINATA","codigodepartamento":"54"},
    {"codigo":"743","nombre":"SILOS","codigodepartamento":"54"},
    {"codigo":"800","nombre":"TEORAMA","codigodepartamento":"54"},
    {"codigo":"810","nombre":"TIBU","codigodepartamento":"54"},
    {"codigo":"820","nombre":"TOLEDO","codigodepartamento":"54"},
    {"codigo":"871","nombre":"VILLA CARO","codigodepartamento":"54"},
    {"codigo":"874","nombre":"VILLA DEL ROSARIO","codigodepartamento":"54"},
    {"codigo":"001","nombre":"ARMENIA","codigodepartamento":"63"},
    {"codigo":"111","nombre":"BUENAVISTA","codigodepartamento":"63"},
    {"codigo":"130","nombre":"CALARCA","codigodepartamento":"63"},
    {"codigo":"190","nombre":"CIRCASIA","codigodepartamento":"63"},
    {"codigo":"212","nombre":"CORDOBA","codigodepartamento":"63"},
    {"codigo":"272","nombre":"FILANDIA","codigodepartamento":"63"},
    {"codigo":"302","nombre":"GENOVA","codigodepartamento":"63"},
    {"codigo":"401","nombre":"LA TEBAIDA","codigodepartamento":"63"},
    {"codigo":"470","nombre":"MONTENEGRO","codigodepartamento":"63"},
    {"codigo":"548","nombre":"PIJAO","codigodepartamento":"63"},
    {"codigo":"594","nombre":"QUIMBAYA","codigodepartamento":"63"},
    {"codigo":"690","nombre":"SALENTO","codigodepartamento":"63"},
    {"codigo":"001","nombre":"PEREIRA","codigodepartamento":"66"},
    {"codigo":"045","nombre":"APIA","codigodepartamento":"66"},
    {"codigo":"075","nombre":"BALBOA","codigodepartamento":"66"},
    {"codigo":"088","nombre":"BELEN DE UMBRIA","codigodepartamento":"66"},
    {"codigo":"170","nombre":"DOS QUEBRADAS","codigodepartamento":"66"},
    {"codigo":"318","nombre":"GUATICA","codigodepartamento":"66"},
    {"codigo":"383","nombre":"LA CELIA","codigodepartamento":"66"},
    {"codigo":"400","nombre":"LA VIRGINIA","codigodepartamento":"66"},
    {"codigo":"440","nombre":"MARSELLA","codigodepartamento":"66"},
    {"codigo":"456","nombre":"MISTRATO","codigodepartamento":"66"},
    {"codigo":"572","nombre":"PUEBLO RICO","codigodepartamento":"66"},
    {"codigo":"594","nombre":"QUINCHIA","codigodepartamento":"66"},
    {"codigo":"682","nombre":"SANTA ROSA DE CABAL","codigodepartamento":"66"},
    {"codigo":"687","nombre":"SANTUARIO","codigodepartamento":"66"},
    {"codigo":"001","nombre":"BUCARAMANGA","codigodepartamento":"68"},
    {"codigo":"013","nombre":"AGUADA","codigodepartamento":"68"},
    {"codigo":"020","nombre":"ALBANIA","codigodepartamento":"68"},
    {"codigo":"051","nombre":"ARATOCA","codigodepartamento":"68"},
    {"codigo":"077","nombre":"BARBOSA","codigodepartamento":"68"},
    {"codigo":"079","nombre":"BARICHARA","codigodepartamento":"68"},
    {"codigo":"081","nombre":"BARRANCABERMEJA","codigodepartamento":"68"},
    {"codigo":"092","nombre":"BETULIA","codigodepartamento":"68"},
    {"codigo":"101","nombre":"BOLIVAR","codigodepartamento":"68"},
    {"codigo":"121","nombre":"CABRERA","codigodepartamento":"68"},
    {"codigo":"132","nombre":"CALIFORNIA","codigodepartamento":"68"},
    {"codigo":"147","nombre":"CAPITANEJO","codigodepartamento":"68"},
    {"codigo":"152","nombre":"CARCASI","codigodepartamento":"68"},
    {"codigo":"160","nombre":"CEPITA","codigodepartamento":"68"},
    {"codigo":"162","nombre":"CERRITO","codigodepartamento":"68"},
    {"codigo":"167","nombre":"CHARALA","codigodepartamento":"68"},
    {"codigo":"169","nombre":"CHARTA","codigodepartamento":"68"},
    {"codigo":"176","nombre":"CHIMA","codigodepartamento":"68"},
    {"codigo":"179","nombre":"CHIPATA","codigodepartamento":"68"},
    {"codigo":"190","nombre":"CIMITARRA","codigodepartamento":"68"},
    {"codigo":"207","nombre":"CONCEPCION","codigodepartamento":"68"},
    {"codigo":"209","nombre":"CONFINES","codigodepartamento":"68"},
    {"codigo":"211","nombre":"CONTRATACION","codigodepartamento":"68"},
    {"codigo":"217","nombre":"COROMORO","codigodepartamento":"68"},
    {"codigo":"229","nombre":"CURITI","codigodepartamento":"68"},
    {"codigo":"235","nombre":"EL CARMEN DE CHUCURI","codigodepartamento":"68"},
    {"codigo":"245","nombre":"EL GUACAMAYO","codigodepartamento":"68"},
    {"codigo":"250","nombre":"EL PEÑON","codigodepartamento":"68"},
    {"codigo":"255","nombre":"EL PLAYON","codigodepartamento":"68"},
    {"codigo":"264","nombre":"ENCINO","codigodepartamento":"68"},
    {"codigo":"266","nombre":"ENCISO","codigodepartamento":"68"},
    {"codigo":"271","nombre":"EL FLORIAN","codigodepartamento":"68"},
    {"codigo":"276","nombre":"FLORIDABLANCA","codigodepartamento":"68"},
    {"codigo":"296","nombre":"GALAN","codigodepartamento":"68"},
    {"codigo":"298","nombre":"GAMBITA","codigodepartamento":"68"},
    {"codigo":"307","nombre":"GIRON","codigodepartamento":"68"},
    {"codigo":"318","nombre":"GUACA","codigodepartamento":"68"},
    {"codigo":"320","nombre":"GUADALUPE","codigodepartamento":"68"},
    {"codigo":"322","nombre":"GUAPOTA","codigodepartamento":"68"},
    {"codigo":"324","nombre":"GUAVATA","codigodepartamento":"68"},
    {"codigo":"327","nombre":"GÜEPSA","codigodepartamento":"68"},
    {"codigo":"344","nombre":"HATO","codigodepartamento":"68"},
    {"codigo":"368","nombre":"JESUS MARIA","codigodepartamento":"68"},
    {"codigo":"370","nombre":"JORDAN","codigodepartamento":"68"},
    {"codigo":"377","nombre":"LA BELLEZA","codigodepartamento":"68"},
    {"codigo":"385","nombre":"LANDAZURI","codigodepartamento":"68"},
    {"codigo":"397","nombre":"LA PAZ","codigodepartamento":"68"},
    {"codigo":"406","nombre":"LEBRIJA","codigodepartamento":"68"},
    {"codigo":"418","nombre":"LOS SANTOS","codigodepartamento":"68"},
    {"codigo":"425","nombre":"MACARAVITA","codigodepartamento":"68"},
    {"codigo":"432","nombre":"MALAGA","codigodepartamento":"68"},
    {"codigo":"444","nombre":"MATANZA","codigodepartamento":"68"},
    {"codigo":"464","nombre":"MOGOTES","codigodepartamento":"68"},
    {"codigo":"468","nombre":"MOLAGAVITA","codigodepartamento":"68"},
    {"codigo":"498","nombre":"OCAMONTE","codigodepartamento":"68"},
    {"codigo":"500","nombre":"OIBA","codigodepartamento":"68"},
    {"codigo":"502","nombre":"ONZAGA","codigodepartamento":"68"},
    {"codigo":"522","nombre":"PALMAR","codigodepartamento":"68"},
    {"codigo":"524","nombre":"PALMAS DEL SOCORRO","codigodepartamento":"68"},
    {"codigo":"533","nombre":"PARAMO","codigodepartamento":"68"},
    {"codigo":"547","nombre":"PIEDECUESTA","codigodepartamento":"68"},
    {"codigo":"549","nombre":"PINCHOTE","codigodepartamento":"68"},
    {"codigo":"572","nombre":"PUENTE NACIONAL","codigodepartamento":"68"},
    {"codigo":"573","nombre":"PUERTO PARRA","codigodepartamento":"68"},
    {"codigo":"575","nombre":"PUERTO WILCHES","codigodepartamento":"68"},
    {"codigo":"615","nombre":"RIONEGRO","codigodepartamento":"68"},
    {"codigo":"655","nombre":"SABANA DE TORRES","codigodepartamento":"68"},
    {"codigo":"669","nombre":"SAN ANDRES","codigodepartamento":"68"},
    {"codigo":"673","nombre":"SAN BENITO","codigodepartamento":"68"},
    {"codigo":"679","nombre":"SAN GIL","codigodepartamento":"68"},
    {"codigo":"682","nombre":"SAN JOAQUIN","codigodepartamento":"68"},
    {"codigo":"684","nombre":"SAN JOSE DE MIRANDA","codigodepartamento":"68"},
    {"codigo":"686","nombre":"SAN MIGUEL","codigodepartamento":"68"},
    {"codigo":"689","nombre":"SAN VICENTE DE CHUCURI","codigodepartamento":"68"},
    {"codigo":"705","nombre":"SANTA BARBARA","codigodepartamento":"68"},
    {"codigo":"720","nombre":"SANTA HELENA DEL OPON","codigodepartamento":"68"},
    {"codigo":"745","nombre":"SIMACOTA","codigodepartamento":"68"},
    {"codigo":"755","nombre":"SOCORRO","codigodepartamento":"68"},
    {"codigo":"770","nombre":"SUAITA","codigodepartamento":"68"},
    {"codigo":"773","nombre":"SUCRE","codigodepartamento":"68"},
    {"codigo":"780","nombre":"SURATA","codigodepartamento":"68"},
    {"codigo":"820","nombre":"TONA","codigodepartamento":"68"},
    {"codigo":"855","nombre":"VALLE SAN JOSE","codigodepartamento":"68"},
    {"codigo":"861","nombre":"VELEZ","codigodepartamento":"68"},
    {"codigo":"867","nombre":"VETAS","codigodepartamento":"68"},
    {"codigo":"872","nombre":"VILLANUEVA","codigodepartamento":"68"},
    {"codigo":"895","nombre":"ZAPATOCA","codigodepartamento":"68"},
    {"codigo":"001","nombre":"SINCELEJO","codigodepartamento":"70"},
    {"codigo":"110","nombre":"BUENAVISTA","codigodepartamento":"70"},
    {"codigo":"124","nombre":"CAIMITO","codigodepartamento":"70"},
    {"codigo":"204","nombre":"COLOSO","codigodepartamento":"70"},
    {"codigo":"215","nombre":"COROZAL","codigodepartamento":"70"},
    {"codigo":"221","nombre":"COVEÑAS","codigodepartamento":"70"},
    {"codigo":"230","nombre":"CHALAN","codigodepartamento":"70"},
    {"codigo":"233","nombre":"EL ROBLE","codigodepartamento":"70"},
    {"codigo":"235","nombre":"GALERAS","codigodepartamento":"70"},
    {"codigo":"265","nombre":"GUARANDA","codigodepartamento":"70"},
    {"codigo":"400","nombre":"LA UNION","codigodepartamento":"70"},
    {"codigo":"418","nombre":"LOS PALMITOS","codigodepartamento":"70"},
    {"codigo":"429","nombre":"MAJAGUAL","codigodepartamento":"70"},
    {"codigo":"473","nombre":"MORROA","codigodepartamento":"70"},
    {"codigo":"508","nombre":"OVEJAS","codigodepartamento":"70"},
    {"codigo":"523","nombre":"PALMITO","codigodepartamento":"70"},
    {"codigo":"670","nombre":"SAMPUES","codigodepartamento":"70"},
    {"codigo":"678","nombre":"SAN BENITO ABAD","codigodepartamento":"70"},
    {"codigo":"702","nombre":"SAN JUAN BETULIA","codigodepartamento":"70"},
    {"codigo":"708","nombre":"SAN MARCOS","codigodepartamento":"70"},
    {"codigo":"713","nombre":"SAN ONOFRE","codigodepartamento":"70"},
    {"codigo":"717","nombre":"SAN PEDRO","codigodepartamento":"70"},
    {"codigo":"742","nombre":"SINCE","codigodepartamento":"70"},
    {"codigo":"771","nombre":"SUCRE","codigodepartamento":"70"},
    {"codigo":"820","nombre":"SANTIAGO DE TOLÚ","codigodepartamento":"70"},
    {"codigo":"823","nombre":"TOLÚ VIEJO","codigodepartamento":"70"},
    {"codigo":"001","nombre":"IBAGUE","codigodepartamento":"73"},
    {"codigo":"024","nombre":"ALPUJARRA","codigodepartamento":"73"},
    {"codigo":"026","nombre":"ALVARADO","codigodepartamento":"73"},
    {"codigo":"030","nombre":"AMBALEMA","codigodepartamento":"73"},
    {"codigo":"043","nombre":"ANZOATEGUI","codigodepartamento":"73"},
    {"codigo":"055","nombre":"ARMERO","codigodepartamento":"73"},
    {"codigo":"067","nombre":"ATACO","codigodepartamento":"73"},
    {"codigo":"124","nombre":"CAJAMARCA","codigodepartamento":"73"},
    {"codigo":"148","nombre":"CARMEN APICALA","codigodepartamento":"73"},
    {"codigo":"152","nombre":"CASABIANCA","codigodepartamento":"73"},
    {"codigo":"168","nombre":"CHAPARRAL","codigodepartamento":"73"},
    {"codigo":"200","nombre":"COELLO","codigodepartamento":"73"},
    {"codigo":"217","nombre":"COYAIMA","codigodepartamento":"73"},
    {"codigo":"226","nombre":"CUNDAY","codigodepartamento":"73"},
    {"codigo":"236","nombre":"DOLORES","codigodepartamento":"73"},
    {"codigo":"268","nombre":"ESPINAL","codigodepartamento":"73"},
    {"codigo":"270","nombre":"FALAN","codigodepartamento":"73"},
    {"codigo":"275","nombre":"FLANDES","codigodepartamento":"73"},
    {"codigo":"283","nombre":"FRESNO","codigodepartamento":"73"},
    {"codigo":"319","nombre":"GUAMO","codigodepartamento":"73"},
    {"codigo":"347","nombre":"HERVEO","codigodepartamento":"73"},
    {"codigo":"349","nombre":"HONDA","codigodepartamento":"73"},
    {"codigo":"352","nombre":"ICONONZO","codigodepartamento":"73"},
    {"codigo":"408","nombre":"LERIDA","codigodepartamento":"73"},
    {"codigo":"411","nombre":"LIBANO","codigodepartamento":"73"},
    {"codigo":"443","nombre":"MARIQUITA","codigodepartamento":"73"},
    {"codigo":"449","nombre":"MELGAR","codigodepartamento":"73"},
    {"codigo":"461","nombre":"MURILLO","codigodepartamento":"73"},
    {"codigo":"483","nombre":"NATAGAIMA","codigodepartamento":"73"},
    {"codigo":"504","nombre":"ORTEGA","codigodepartamento":"73"},
    {"codigo":"520","nombre":"PALOCABILDO","codigodepartamento":"73"},
    {"codigo":"547","nombre":"PIEDRAS","codigodepartamento":"73"},
    {"codigo":"555","nombre":"PLANADAS","codigodepartamento":"73"},
    {"codigo":"563","nombre":"PRADO","codigodepartamento":"73"},
    {"codigo":"585","nombre":"PURIFICACION","codigodepartamento":"73"},
    {"codigo":"616","nombre":"RIOBLANCO","codigodepartamento":"73"},
    {"codigo":"622","nombre":"RONCESVALLES","codigodepartamento":"73"},
    {"codigo":"624","nombre":"ROVIRA","codigodepartamento":"73"},
    {"codigo":"671","nombre":"SALDAÑA","codigodepartamento":"73"},
    {"codigo":"675","nombre":"SAN ANTONIO","codigodepartamento":"73"},
    {"codigo":"678","nombre":"SAN LUIS","codigodepartamento":"73"},
    {"codigo":"686","nombre":"SANTA ISABEL","codigodepartamento":"73"},
    {"codigo":"770","nombre":"SUAREZ","codigodepartamento":"73"},
    {"codigo":"854","nombre":"VALLE DE SAN JUAN","codigodepartamento":"73"},
    {"codigo":"861","nombre":"VENADILLO","codigodepartamento":"73"},
    {"codigo":"870","nombre":"VILLAHERMOSA","codigodepartamento":"73"},
    {"codigo":"873","nombre":"VILLARRICA","codigodepartamento":"73"},
    {"codigo":"001","nombre":"CALI","codigodepartamento":"76"},
    {"codigo":"020","nombre":"ALCALA","codigodepartamento":"76"},
    {"codigo":"036","nombre":"ANDALUCIA","codigodepartamento":"76"},
    {"codigo":"041","nombre":"ANSERMANUEVO","codigodepartamento":"76"},
    {"codigo":"054","nombre":"ARGELIA","codigodepartamento":"76"},
    {"codigo":"100","nombre":"BOLIVAR","codigodepartamento":"76"},
    {"codigo":"109","nombre":"BUENAVENTURA","codigodepartamento":"76"},
    {"codigo":"111","nombre":"GUADALAJARA DE BUGA","codigodepartamento":"76"},
    {"codigo":"113","nombre":"BUGALAGRANDE","codigodepartamento":"76"},
    {"codigo":"122","nombre":"CAICEDONIA","codigodepartamento":"76"},
    {"codigo":"126","nombre":"CALIMA","codigodepartamento":"76"},
    {"codigo":"130","nombre":"CANDELARIA","codigodepartamento":"76"},
    {"codigo":"147","nombre":"CARTAGO","codigodepartamento":"76"},
    {"codigo":"233","nombre":"DAGUA","codigodepartamento":"76"},
    {"codigo":"243","nombre":"EL AGUILA","codigodepartamento":"76"},
    {"codigo":"246","nombre":"EL CAIRO","codigodepartamento":"76"},
    {"codigo":"248","nombre":"EL CERRITO","codigodepartamento":"76"},
    {"codigo":"250","nombre":"EL DOVIO","codigodepartamento":"76"},
    {"codigo":"275","nombre":"FLORIDA","codigodepartamento":"76"},
    {"codigo":"306","nombre":"GINEBRA","codigodepartamento":"76"},
    {"codigo":"318","nombre":"GUACARI","codigodepartamento":"76"},
    {"codigo":"364","nombre":"JAMUNDI","codigodepartamento":"76"},
    {"codigo":"377","nombre":"LA CUMBRE","codigodepartamento":"76"},
    {"codigo":"400","nombre":"LA UNION","codigodepartamento":"76"},
    {"codigo":"403","nombre":"LA VICTORIA","codigodepartamento":"76"},
    {"codigo":"497","nombre":"OBANDO","codigodepartamento":"76"},
    {"codigo":"520","nombre":"PALMIRA","codigodepartamento":"76"},
    {"codigo":"563","nombre":"PRADERA","codigodepartamento":"76"},
    {"codigo":"606","nombre":"RESTREPO","codigodepartamento":"76"},
    {"codigo":"616","nombre":"RIOFRIO","codigodepartamento":"76"},
    {"codigo":"622","nombre":"ROLDANILLO","codigodepartamento":"76"},
    {"codigo":"670","nombre":"SAN PEDRO","codigodepartamento":"76"},
    {"codigo":"736","nombre":"SEVILLA","codigodepartamento":"76"},
    {"codigo":"823","nombre":"TORO","codigodepartamento":"76"},
    {"codigo":"828","nombre":"TRUJILLO","codigodepartamento":"76"},
    {"codigo":"834","nombre":"TULUA","codigodepartamento":"76"},
    {"codigo":"845","nombre":"ULLOA","codigodepartamento":"76"},
    {"codigo":"863","nombre":"VERSALLES","codigodepartamento":"76"},
    {"codigo":"869","nombre":"VIJES","codigodepartamento":"76"},
    {"codigo":"890","nombre":"YOTOCO","codigodepartamento":"76"},
    {"codigo":"892","nombre":"YUMBO","codigodepartamento":"76"},
    {"codigo":"895","nombre":"ZARZAL","codigodepartamento":"76"},
    {"codigo":"001","nombre":"ARAUCA","codigodepartamento":"81"},
    {"codigo":"065","nombre":"ARAUQUITA","codigodepartamento":"81"},
    {"codigo":"220","nombre":"CRAVO NORTE","codigodepartamento":"81"},
    {"codigo":"300","nombre":"FORTUL","codigodepartamento":"81"},
    {"codigo":"591","nombre":"PUERTO RONDON","codigodepartamento":"81"},
    {"codigo":"736","nombre":"SARAVENA","codigodepartamento":"81"},
    {"codigo":"794","nombre":"TAME","codigodepartamento":"81"},
    {"codigo":"001","nombre":"YOPAL","codigodepartamento":"85"},
    {"codigo":"010","nombre":"AGUAZUL","codigodepartamento":"85"},
    {"codigo":"015","nombre":"CHAMEZA","codigodepartamento":"85"},
    {"codigo":"125","nombre":"HATO COROZAL","codigodepartamento":"85"},
    {"codigo":"136","nombre":"LA SALINA","codigodepartamento":"85"},
    {"codigo":"139","nombre":"MANI","codigodepartamento":"85"},
    {"codigo":"162","nombre":"MONTERREY","codigodepartamento":"85"},
    {"codigo":"225","nombre":"NUNCHIA","codigodepartamento":"85"},
    {"codigo":"230","nombre":"OROCUE","codigodepartamento":"85"},
    {"codigo":"250","nombre":"PAZ DE ARIPORO","codigodepartamento":"85"},
    {"codigo":"263","nombre":"PORE","codigodepartamento":"85"},
    {"codigo":"279","nombre":"RECETOR","codigodepartamento":"85"},
    {"codigo":"300","nombre":"SABANALARGA","codigodepartamento":"85"},
    {"codigo":"315","nombre":"SACAMA","codigodepartamento":"85"},
    {"codigo":"325","nombre":"SAN LUIS DE PALENQUE","codigodepartamento":"85"},
    {"codigo":"400","nombre":"TAMARA","codigodepartamento":"85"},
    {"codigo":"410","nombre":"TAURAMENA","codigodepartamento":"85"},
    {"codigo":"430","nombre":"TRINIDAD","codigodepartamento":"85"},
    {"codigo":"440","nombre":"VILLANUEVA","codigodepartamento":"85"},
    {"codigo":"001","nombre":"MOCOA","codigodepartamento":"86"},
    {"codigo":"219","nombre":"COLON","codigodepartamento":"86"},
    {"codigo":"320","nombre":"ORITO","codigodepartamento":"86"},
    {"codigo":"568","nombre":"PUERTO ASIS","codigodepartamento":"86"},
    {"codigo":"569","nombre":"PUERTO CAICEDO","codigodepartamento":"86"},
    {"codigo":"571","nombre":"PUERTO GUZMAN","codigodepartamento":"86"},
    {"codigo":"573","nombre":"LEGUÍZAMO","codigodepartamento":"86"},
    {"codigo":"749","nombre":"SIBUNDOY","codigodepartamento":"86"},
    {"codigo":"755","nombre":"SAN FRANCISCO","codigodepartamento":"86"},
    {"codigo":"757","nombre":"SAN MIGUEL","codigodepartamento":"86"},
    {"codigo":"760","nombre":"SANTIAGO","codigodepartamento":"86"},
    {"codigo":"865","nombre":"VALLE DEL GUAMUEZ","codigodepartamento":"86"},
    {"codigo":"885","nombre":"VILLAGARZON","codigodepartamento":"86"},
    {"codigo":"001","nombre":"SAN ANDRES","codigodepartamento":"88"},
    {"codigo":"564","nombre":"PROVIDENCIA Y SANTA CATALINA","codigodepartamento":"88"},
    {"codigo":"001","nombre":"LETICIA","codigodepartamento":"91"},
    {"codigo":"263","nombre":"EL ENCANTO","codigodepartamento":"91"},
    {"codigo":"405","nombre":"LA CHORRERA","codigodepartamento":"91"},
    {"codigo":"407","nombre":"LA PEDRERA","codigodepartamento":"91"},
    {"codigo":"430","nombre":"LA VICTORIA","codigodepartamento":"91"},
    {"codigo":"460","nombre":"MIRITI-PARANA","codigodepartamento":"91"},
    {"codigo":"530","nombre":"PUERTO ALEGRIA","codigodepartamento":"91"},
    {"codigo":"536","nombre":"PUERTO ARICA","codigodepartamento":"91"},
    {"codigo":"540","nombre":"PUERTO NARIÑO","codigodepartamento":"91"},
    {"codigo":"669","nombre":"PUERTO SANTANDER","codigodepartamento":"91"},
    {"codigo":"798","nombre":"TARAPACA","codigodepartamento":"91"},
    {"codigo":"001","nombre":"INIRIDA","codigodepartamento":"94"},
    {"codigo":"343","nombre":"BARRANCO MINA","codigodepartamento":"94"},
    {"codigo":"663","nombre":"MAPIRIPANA","codigodepartamento":"94"},
    {"codigo":"883","nombre":"SAN FELIPE","codigodepartamento":"94"},
    {"codigo":"884","nombre":"PUERTO COLOMBIA","codigodepartamento":"94"},
    {"codigo":"885","nombre":"LA GUADALUPE","codigodepartamento":"94"},
    {"codigo":"886","nombre":"CACAHUAL","codigodepartamento":"94"},
    {"codigo":"887","nombre":"PANA PANA","codigodepartamento":"94"},
    {"codigo":"888","nombre":"MORICHAL","codigodepartamento":"94"},
    {"codigo":"001","nombre":"SAN JOSE DEL GUAVIARE","codigodepartamento":"95"},
    {"codigo":"015","nombre":"CALAMAR","codigodepartamento":"95"},
    {"codigo":"025","nombre":"EL RETORNO","codigodepartamento":"95"},
    {"codigo":"200","nombre":"MIRAFLORES","codigodepartamento":"95"},
    {"codigo":"001","nombre":"MITU","codigodepartamento":"97"},
    {"codigo":"161","nombre":"CARURU","codigodepartamento":"97"},
    {"codigo":"511","nombre":"PACOA","codigodepartamento":"97"},
    {"codigo":"666","nombre":"TARAIRA","codigodepartamento":"97"},
    {"codigo":"777","nombre":"PAPUNAHUA","codigodepartamento":"97"},
    {"codigo":"889","nombre":"YAVARATE","codigodepartamento":"97"},
    {"codigo":"001","nombre":"PUERTO CARREÑO","codigodepartamento":"99"},
    {"codigo":"524","nombre":"LA PRIMAVERA","codigodepartamento":"99"},
    {"codigo":"624","nombre":"SANTA ROSALIA","codigodepartamento":"99"},
    {"codigo":"773","nombre":"CUMARIBO","codigodepartamento":"99"}
    ]